"""POST /v1/ingest: persistence, idempotency, and the partition window.

Tenant isolation is covered separately in test_tenant_isolation.py. What is
under test here is that a batch survives the round trip intact - that the
OpenTelemetry field aliases land in the right columns, that cost is computed by
the server and not taken from the client, that a retry does not duplicate, and
that a timestamp outside the partitioned range is refused rather than stranded.
"""

from datetime import UTC, datetime, timedelta
from decimal import Decimal
from typing import Any
from uuid import UUID, uuid4

import pytest
from httpx import AsyncClient
from sqlalchemy import text

from tests.conftest import Tenant, tenant_session


def _now() -> datetime:
    # Whole seconds: the payload round-trips through ISO-8601 and the assertions
    # below compare against what was sent.
    return datetime.now(UTC).replace(microsecond=0)


async def _scalar(project_id: UUID, sql: str, **params: Any) -> Any:
    async with tenant_session(project_id) as session:
        return await session.scalar(text(sql), params)


# --------------------------------------------------------------------------
# Round trip
# --------------------------------------------------------------------------


async def test_batch_is_accepted_and_counted(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    a, _ = tenants
    response = await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {"id": str(uuid4()), "name": "t1", "observations": [{"id": str(uuid4())}]},
                {"id": str(uuid4()), "name": "t2", "observations": []},
            ]
        },
        headers=a.headers,
    )
    assert response.status_code == 202
    assert response.json() == {
        "accepted_traces": 2,
        "accepted_observations": 1,
        "accepted_scores": 0,
        "rejected_observations": 0,
        "rejected_scores": 0,
    }


async def test_observation_fields_land_in_the_right_columns(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """Exercises the OTel aliases, the generated column, and server-side cost."""
    a, _ = tenants
    t0 = _now()
    obs_id = uuid4()

    response = await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "started_at": t0.isoformat(),
                    "observations": [
                        {
                            "id": str(obs_id),
                            "type": "generation",
                            "gen_ai.request.model": "claude-opus-5-20260115",
                            "gen_ai.system": "anthropic",
                            "gen_ai.usage.input_tokens": 1000,
                            "gen_ai.usage.output_tokens": 500,
                            "start_time": t0.isoformat(),
                            "end_time": (t0 + timedelta(milliseconds=1234)).isoformat(),
                            "input": {"messages": [{"role": "user", "content": "hi"}]},
                            "output": {"text": "hello"},
                        }
                    ],
                }
            ]
        },
        headers=a.headers,
    )
    assert response.status_code == 202

    async with tenant_session(a.project_id) as session:
        row = (
            await session.execute(
                text(
                    "SELECT model, provider, prompt_tokens, completion_tokens, "
                    "total_tokens, cost_usd, latency_ms, type, input->>'messages' IS NOT NULL "
                    "FROM observations WHERE id = :i"
                ),
                {"i": obs_id},
            )
        ).first()

    assert row is not None
    model, provider, prompt, completion, total, cost, latency, type_, has_input = row
    assert model == "claude-opus-5-20260115"
    assert provider == "anthropic"
    assert (prompt, completion) == (1000, 500)
    assert total == 1500, "total_tokens is generated by the database"
    assert cost == Decimal("0.01750000"), "cost computed server-side at write time"
    assert latency == 1234, "latency derived from the timestamps"
    assert type_ == "generation"
    assert has_input is True


async def test_client_supplied_cost_is_ignored(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """Rule 3: cost is computed server-side and frozen, never taken on trust."""
    a, _ = tenants
    obs_id = uuid4()

    await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "observations": [
                        {
                            "id": str(obs_id),
                            "model": "gpt-4o",
                            "prompt_tokens": 1_000_000,
                            "completion_tokens": 0,
                            "cost_usd": 99999,
                        }
                    ],
                }
            ]
        },
        headers=a.headers,
    )

    cost = await _scalar(a.project_id, "SELECT cost_usd FROM observations WHERE id = :i", i=obs_id)
    assert cost == Decimal("2.50000000")


async def test_unknown_model_stores_null_cost(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """Not zero. Zero would claim the call was free."""
    a, _ = tenants
    obs_id = uuid4()

    await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "observations": [
                        {
                            "id": str(obs_id),
                            "model": "some-model-released-next-year",
                            "prompt_tokens": 10,
                            "completion_tokens": 10,
                        }
                    ],
                }
            ]
        },
        headers=a.headers,
    )

    async with tenant_session(a.project_id) as session:
        row = (
            await session.execute(
                text("SELECT cost_usd, prompt_tokens FROM observations WHERE id = :i"),
                {"i": obs_id},
            )
        ).first()
    assert row is not None
    assert row[0] is None, "unpriced model must not be costed"
    assert row[1] == 10, "the rest of the observation is still stored"


async def test_unknown_fields_are_accepted(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """Rule 5: a newer SDK sending extra keys must not be 4xxed."""
    a, _ = tenants
    response = await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "name": "forward-compatible",
                    "a_field_from_the_future": {"nested": [1, 2, 3]},
                    "observations": [{"id": str(uuid4()), "another_new_key": "ignored"}],
                }
            ],
            "an_unknown_top_level_key": True,
        },
        headers=a.headers,
    )
    assert response.status_code == 202
    assert await _scalar(a.project_id, "SELECT count(*) FROM traces") == 1


# --------------------------------------------------------------------------
# Idempotency
# --------------------------------------------------------------------------


async def test_replaying_a_batch_creates_no_duplicates(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """Rule 4: clients retry, and duplicate ids must not create duplicate rows."""
    a, _ = tenants
    t0 = _now()
    payload = {
        "traces": [
            {
                "id": str(uuid4()),
                "name": "retried",
                "started_at": t0.isoformat(),
                "observations": [{"id": str(uuid4()), "start_time": t0.isoformat()}],
            }
        ]
    }

    for _ in range(3):
        response = await client.post("/v1/ingest", json=payload, headers=a.headers)
        assert response.status_code == 202

    assert await _scalar(a.project_id, "SELECT count(*) FROM traces") == 1
    assert await _scalar(a.project_id, "SELECT count(*) FROM observations") == 1


async def test_a_later_batch_closes_the_trace(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """The reason traces upsert rather than DO NOTHING.

    The SDK sends a trace when the run starts and again when it ends. Under
    ON CONFLICT DO NOTHING the second write is discarded and ended_at is never
    recorded - so the merge is what makes the close observable at all.
    """
    a, _ = tenants
    t0 = _now()
    trace_id = uuid4()

    await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(trace_id),
                    "name": "long-run",
                    "user_id": "u-1",
                    "started_at": t0.isoformat(),
                    "metadata": {"env": "prod"},
                }
            ]
        },
        headers=a.headers,
    )
    await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(trace_id),
                    "ended_at": (t0 + timedelta(seconds=5)).isoformat(),
                    "metadata": {"region": "eu"},
                }
            ]
        },
        headers=a.headers,
    )

    async with tenant_session(a.project_id) as session:
        row = (
            await session.execute(
                text(
                    "SELECT name, user_id, ended_at IS NOT NULL, "
                    "metadata->>'env', metadata->>'region' FROM traces WHERE id = :t"
                ),
                {"t": trace_id},
            )
        ).first()

    assert row is not None
    name, user_id, closed, env, region = row
    assert closed is True, "ended_at must be recorded by the second batch"
    assert name == "long-run", "a partial batch must not blank an existing name"
    assert user_id == "u-1"
    assert (env, region) == ("prod", "eu"), "metadata merges rather than replacing"


# --------------------------------------------------------------------------
# Out-of-order delivery
# --------------------------------------------------------------------------


async def test_observations_arriving_before_their_trace_create_a_stub(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """observations.trace_id carries no FK so that this cannot reject the write."""
    a, _ = tenants
    orphan_id = uuid4()

    await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "observations": [{"id": str(uuid4()), "trace_id": str(orphan_id)}],
                }
            ]
        },
        headers=a.headers,
    )

    async with tenant_session(a.project_id) as session:
        row = (
            await session.execute(
                text("SELECT name, started_at IS NOT NULL FROM traces WHERE id = :t"),
                {"t": orphan_id},
            )
        ).first()
    assert row == (None, True), "a nameless placeholder with a usable timestamp"


async def test_the_real_trace_overwrites_its_stub(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """The other half of the asymmetry: stubs DO NOTHING, real traces merge."""
    a, _ = tenants
    trace_id = uuid4()

    await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "observations": [{"id": str(uuid4()), "trace_id": str(trace_id)}],
                }
            ]
        },
        headers=a.headers,
    )
    await client.post(
        "/v1/ingest",
        json={"traces": [{"id": str(trace_id), "name": "arrived-late", "user_id": "u-2"}]},
        headers=a.headers,
    )

    async with tenant_session(a.project_id) as session:
        row = (
            await session.execute(
                text("SELECT name, user_id FROM traces WHERE id = :t"), {"t": trace_id}
            )
        ).first()
    assert row == ("arrived-late", "u-2")


async def test_a_stub_never_overwrites_a_real_trace(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    a, _ = tenants
    trace_id = uuid4()

    await client.post(
        "/v1/ingest",
        json={"traces": [{"id": str(trace_id), "name": "the-real-one"}]},
        headers=a.headers,
    )
    await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "observations": [{"id": str(uuid4()), "trace_id": str(trace_id)}],
                }
            ]
        },
        headers=a.headers,
    )

    name = await _scalar(a.project_id, "SELECT name FROM traces WHERE id = :t", t=trace_id)
    assert name == "the-real-one"


# --------------------------------------------------------------------------
# Partition window
# --------------------------------------------------------------------------


async def test_out_of_window_observations_are_rejected_individually(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """One skewed clock must not cost the rest of the batch."""
    a, _ = tenants
    t0 = _now()
    good, too_old, too_new = uuid4(), uuid4(), uuid4()

    response = await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "name": "clock-skew",
                    "started_at": t0.isoformat(),
                    "observations": [
                        {"id": str(good), "start_time": t0.isoformat()},
                        {"id": str(too_old), "start_time": (t0 - timedelta(days=30)).isoformat()},
                        {"id": str(too_new), "start_time": (t0 + timedelta(days=10)).isoformat()},
                    ],
                }
            ]
        },
        headers=a.headers,
    )

    assert response.status_code == 202, "a bad timestamp is not a bad request"
    assert response.json() == {
        "accepted_traces": 1,
        "accepted_observations": 1,
        "accepted_scores": 0,
        "rejected_observations": 2,
        "rejected_scores": 0,
    }

    assert (
        await _scalar(a.project_id, "SELECT count(*) FROM observations WHERE id = :i", i=good) == 1
    )
    for rejected in (too_old, too_new):
        assert (
            await _scalar(
                a.project_id, "SELECT count(*) FROM observations WHERE id = :i", i=rejected
            )
            == 0
        )

    assert await _scalar(a.project_id, "SELECT count(*) FROM traces") == 1, (
        "the trace is still recorded even though its observations were dropped"
    )


async def test_nothing_reaches_the_default_partition(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """The whole point of the window.

    A row in observations_default permanently costs its day a partition:
    ensure_observations_partitions() warns and skips any day whose rows are
    already stranded, so every later write for that day lands in DEFAULT too and
    stops being pruned.
    """
    a, _ = tenants
    t0 = _now()

    await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "observations": [
                        {"id": str(uuid4()), "start_time": (t0 + delta).isoformat()}
                        for delta in (
                            timedelta(0),
                            timedelta(days=-365),
                            timedelta(days=365),
                            timedelta(days=-8),
                            timedelta(days=2),
                        )
                    ],
                }
            ]
        },
        headers=a.headers,
    )

    stranded = await _scalar(
        a.project_id,
        "SELECT count(*) FROM observations WHERE tableoid = 'observations_default'::regclass",
    )
    assert stranded == 0


@pytest.mark.parametrize(
    ("label", "delta"),
    [
        ("oldest accepted", timedelta(days=-6, hours=-23)),
        ("newest accepted", timedelta(hours=23)),
        ("now", timedelta(0)),
    ],
)
async def test_accepted_timestamps_route_to_a_named_partition(
    tenants: tuple[Tenant, Tenant], client: AsyncClient, label: str, delta: timedelta
) -> None:
    """Everything inside the accepted window must have a partition waiting.

    This is the invariant that ties app.config to migration 0003: the accepted
    range must be a strict subset of the partitioned range. If someone widens
    ingest_max_event_age_days without widening DAYS_BEHIND, this fails.
    """
    a, _ = tenants
    obs_id = uuid4()

    response = await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "observations": [
                        {"id": str(obs_id), "start_time": (_now() + delta).isoformat()}
                    ],
                }
            ]
        },
        headers=a.headers,
    )
    assert response.json()["rejected_observations"] == 0, f"{label} should be accepted"

    partition = await _scalar(
        a.project_id,
        "SELECT tableoid::regclass::text FROM observations WHERE id = :i",
        i=obs_id,
    )
    assert partition is not None
    assert partition != "observations_default", f"{label} was stranded in DEFAULT"
    assert partition.startswith("observations_p"), partition


# --------------------------------------------------------------------------
# Size limits
# --------------------------------------------------------------------------


async def test_too_many_traces_is_refused(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """422 rather than 413: the schema's max_length rejects during parsing.

    That ordering is deliberate - it avoids materialising an oversized list
    before deciding to refuse it. The router's 413 applies to the observation
    total, which the schema cannot express because its cap is per trace.
    """
    a, _ = tenants
    response = await client.post(
        "/v1/ingest",
        json={"traces": [{"id": str(uuid4())} for _ in range(1001)]},
        headers=a.headers,
    )
    assert response.status_code == 422


async def test_too_many_observations_is_refused(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    a, _ = tenants
    response = await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {
                    "id": str(uuid4()),
                    "observations": [{"id": str(uuid4())} for _ in range(2000)],
                }
                for _ in range(3)
            ]
        },
        headers=a.headers,
    )
    assert response.status_code == 413
    assert "6000" in response.json()["detail"]


# --------------------------------------------------------------------------
# Envelopes
# --------------------------------------------------------------------------


async def test_flat_events_envelope_is_accepted(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """What the Python SDK actually sends: one stream keyed by `type`."""
    a, _ = tenants
    trace_id, obs_id = uuid4(), uuid4()
    t0 = _now()

    response = await client.post(
        "/v1/ingest",
        json={
            "events": [
                {
                    "id": str(trace_id),
                    "type": "trace",
                    "name": "handle-request",
                    "start_time": t0.isoformat(),
                },
                {
                    "id": str(obs_id),
                    "type": "generation",
                    "trace_id": str(trace_id),
                    "name": "completion",
                    "status": "ok",
                    "model": "gpt-4o",
                    "prompt_tokens": 10,
                    "completion_tokens": 5,
                    "start_time": t0.isoformat(),
                },
            ]
        },
        headers=a.headers,
    )
    assert response.status_code == 202
    assert response.json() == {
        "accepted_traces": 1,
        "accepted_observations": 1,
        "accepted_scores": 0,
        "rejected_observations": 0,
        "rejected_scores": 0,
    }

    async with tenant_session(a.project_id) as session:
        trace_name = await session.scalar(
            text("SELECT name FROM traces WHERE id = :t"), {"t": trace_id}
        )
        row = (
            await session.execute(
                text("SELECT name, trace_id, level, cost_usd FROM observations WHERE id = :i"),
                {"i": obs_id},
            )
        ).first()

    assert trace_name == "handle-request"
    assert row is not None
    assert row[0] == "completion"
    assert row[1] == trace_id, "the observation is attributed by its own trace_id"
    assert row[2] == "ok", "SDK `status` folds into level"
    assert row[3] == Decimal("0.00007500")


async def test_an_unrecognised_event_type_is_stored_as_an_observation(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """Only `type == "trace"` changes routing; a new span kind must not 4xx."""
    a, _ = tenants
    obs_id = uuid4()

    response = await client.post(
        "/v1/ingest",
        json={"events": [{"id": str(obs_id), "type": "embedding-v2", "trace_id": str(uuid4())}]},
        headers=a.headers,
    )
    assert response.status_code == 202

    stored = await _scalar(a.project_id, "SELECT type FROM observations WHERE id = :i", i=obs_id)
    assert stored == "embedding-v2"


async def test_both_envelopes_may_appear_together(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    a, _ = tenants
    response = await client.post(
        "/v1/ingest",
        json={
            "traces": [
                {"id": str(uuid4()), "name": "nested", "observations": [{"id": str(uuid4())}]}
            ],
            "events": [{"id": str(uuid4()), "type": "trace", "name": "flat"}],
        },
        headers=a.headers,
    )
    assert response.status_code == 202
    assert response.json()["accepted_traces"] == 2
    assert response.json()["accepted_observations"] == 1


async def test_an_empty_batch_is_accepted(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """A flush with nothing buffered is normal, not an error."""
    a, _ = tenants
    bodies: list[dict[str, Any]] = [{"events": []}, {"traces": []}]
    for body in bodies:
        response = await client.post("/v1/ingest", json=body, headers=a.headers)
        assert response.status_code == 202
        assert response.json()["accepted_traces"] == 0


async def test_an_unrecognised_envelope_is_refused(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """The one place this schema is strict, and deliberately so.

    Accepting `{}` would hand a client with a drifted envelope a 202 and a count
    of zero on every batch - success reported while nothing is stored. This is
    the check that surfaced the SDK mismatch in the first place.
    """
    a, _ = tenants
    response = await client.post("/v1/ingest", json={"records": []}, headers=a.headers)
    assert response.status_code == 422
    assert "events" in response.text and "traces" in response.text


# --------------------------------------------------------------------------
# Numeric coercion
# --------------------------------------------------------------------------


async def test_fractional_latency_is_rounded_not_rejected(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """The SDK times spans with perf_counter and sends sub-millisecond floats.

    Refusing them 422s the whole batch over precision nobody asked for - which
    is exactly what happened the first time the SDK was pointed at this API.
    """
    a, _ = tenants
    obs_id = uuid4()

    response = await client.post(
        "/v1/ingest",
        json={
            "events": [
                {
                    "id": str(obs_id),
                    "type": "span",
                    "trace_id": str(uuid4()),
                    "latency_ms": 50.477910990593955,
                    "prompt_tokens": 10.0,
                }
            ]
        },
        headers=a.headers,
    )
    assert response.status_code == 202

    async with tenant_session(a.project_id) as session:
        row = (
            await session.execute(
                text("SELECT latency_ms, prompt_tokens FROM observations WHERE id = :i"),
                {"i": obs_id},
            )
        ).first()
    assert row == (50, 10)


async def test_a_negative_duration_is_clamped(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """A backwards clock is nonsense, but losing the batch over it is worse."""
    a, _ = tenants
    obs_id = uuid4()

    response = await client.post(
        "/v1/ingest",
        json={
            "events": [
                {
                    "id": str(obs_id),
                    "type": "span",
                    "trace_id": str(uuid4()),
                    "latency_ms": -12.5,
                }
            ]
        },
        headers=a.headers,
    )
    assert response.status_code == 202
    assert (
        await _scalar(a.project_id, "SELECT latency_ms FROM observations WHERE id = :i", i=obs_id)
        == 0
    )


async def test_a_flat_observation_without_a_trace_id_is_kept(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """Unattributable, but derived deterministically so retries do not multiply.

    The trace id is taken from the observation's own id. Minting a fresh uuid
    per request would create a new placeholder trace on every redelivery.

    start_time is sent explicitly because the observations primary key is
    (project_id, id, started_at) - the partition key has to be in it. A client
    that omits the timestamp gets a server-stamped one, which differs per
    request and therefore defeats deduplication. That obligation is on the SDK
    and is documented on the Observation model; it is not something the server
    can paper over.
    """
    a, _ = tenants
    obs_id = uuid4()
    body: dict[str, Any] = {
        "events": [
            {
                "id": str(obs_id),
                "type": "span",
                "name": "orphan",
                "start_time": _now().isoformat(),
            }
        ]
    }

    for _ in range(2):
        response = await client.post("/v1/ingest", json=body, headers=a.headers)
        assert response.status_code == 202

    assert await _scalar(a.project_id, "SELECT count(*) FROM observations") == 1
    assert await _scalar(a.project_id, "SELECT count(*) FROM traces") == 1
    assert (
        await _scalar(a.project_id, "SELECT trace_id FROM observations WHERE id = :i", i=obs_id)
        == obs_id
    ), "the derived trace id is the observation's own, so it is stable"


async def test_an_observation_without_a_timestamp_cannot_deduplicate(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """Pins the known limit of idempotency rather than pretending it is absent.

    started_at is the partition key and Postgres requires it in every unique
    constraint, so it is part of the identity of a row. Without a client-supplied
    timestamp the server stamps its own, and a retry is genuinely a different
    row. Documented on the Observation model as an SDK obligation; asserted here
    so that a future change making retries silently duplicate *with* timestamps
    would still be caught by the test above.
    """
    a, _ = tenants
    obs_id = uuid4()
    body: dict[str, Any] = {"events": [{"id": str(obs_id), "type": "span", "name": "no-timestamp"}]}

    for _ in range(2):
        assert (await client.post("/v1/ingest", json=body, headers=a.headers)).status_code == 202

    assert await _scalar(a.project_id, "SELECT count(*) FROM observations") == 2


# --------------------------------------------------------------------------
# Attribution, token detail, and scores (llm-metrics 0.1.0)
# --------------------------------------------------------------------------


async def test_attribution_fields_land_on_the_trace(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    a, _ = tenants
    trace_id = uuid4()

    response = await client.post(
        "/v1/ingest",
        json={
            "events": [
                {
                    "id": str(trace_id),
                    "type": "trace",
                    "name": "answer",
                    "user_id": "u-1",
                    "session_id": "s-1",
                    "tags": ["qa", " beta ", "qa", 42],
                    "environment": "prod",
                    "release": "3191d7d",
                    "start_time": _now().isoformat(),
                }
            ]
        },
        headers=a.headers,
    )
    assert response.status_code == 202

    async with tenant_session(a.project_id) as session:
        row = (
            await session.execute(
                text("SELECT tags, environment, release FROM traces WHERE id = :t"),
                {"t": trace_id},
            )
        ).first()
    assert row is not None
    assert row[0] == ["qa", "beta"], "trimmed, de-duplicated, non-strings dropped"
    assert row[1] == "prod"
    assert row[2] == "3191d7d"


async def test_a_later_batch_does_not_clear_tags(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """The SDK sends a trace at start and again at end. Tags set in between
    arrive on the second send; a third send with none must keep them."""
    a, _ = tenants
    trace_id = uuid4()
    t0 = _now().isoformat()
    base = {"id": str(trace_id), "type": "trace", "name": "t", "start_time": t0}

    for payload in (
        {**base, "tags": ["beta"], "environment": "prod"},
        {**base, "tags": [], "end_time": t0},
    ):
        response = await client.post("/v1/ingest", json={"events": [payload]}, headers=a.headers)
        assert response.status_code == 202

    async with tenant_session(a.project_id) as session:
        row = (
            await session.execute(
                text("SELECT tags, environment, ended_at FROM traces WHERE id = :t"),
                {"t": trace_id},
            )
        ).first()
    assert row is not None
    assert row[0] == ["beta"]
    assert row[1] == "prod"
    assert row[2] is not None, "the second send still closed the trace"


async def test_token_detail_lands_and_discounts_cached_tokens(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """cached_tokens is a subset of prompt_tokens, priced at the cached rate."""
    a, _ = tenants
    obs_id = uuid4()
    t0 = _now().isoformat()

    response = await client.post(
        "/v1/ingest",
        json={
            "events": [
                {
                    "id": str(obs_id),
                    "type": "generation",
                    "trace_id": str(uuid4()),
                    "model": "gpt-4o",
                    "prompt_tokens": 1000,
                    "completion_tokens": 100,
                    "cached_tokens": 900,
                    "reasoning_tokens": 40,
                    "prompt_name": "qa",
                    "prompt_version": 3,
                    "start_time": t0,
                }
            ]
        },
        headers=a.headers,
    )
    assert response.status_code == 202

    async with tenant_session(a.project_id) as session:
        row = (
            await session.execute(
                text(
                    "SELECT cached_tokens, reasoning_tokens, prompt_name, prompt_version, "
                    "cost_usd, total_tokens FROM observations WHERE id = :i"
                ),
                {"i": obs_id},
            )
        ).first()
    assert row is not None
    cached, reasoning, prompt_name, prompt_version, cost, total = row
    assert (cached, reasoning) == (900, 40)
    assert (prompt_name, prompt_version) == ("qa", "3"), "versions are stored as text"
    # 100 fresh @ $2.50 + 900 cached @ $1.25 + 100 out @ $10, per million.
    assert cost == Decimal("0.00237500")
    assert total == 1100, "total_tokens is unchanged; the detail is a subset"


async def test_scores_are_stored_by_type(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    a, _ = tenants
    trace_id, obs_id = uuid4(), uuid4()
    t0 = _now()
    scores = [
        {
            "id": str(uuid4()),
            "type": "score",
            "trace_id": str(trace_id),
            "name": "thumbs",
            "value": True,
            "source": "human",
            "timestamp": t0.isoformat(),
        },
        {
            "id": str(uuid4()),
            "type": "score",
            "trace_id": str(trace_id),
            "observation_id": str(obs_id),
            "name": "faithfulness",
            "value": 0.875,
            "source": "llm_judge",
            "comment": "cites the doc",
        },
        {
            "id": str(uuid4()),
            "type": "score",
            "observation_id": str(obs_id),
            "name": "category",
            "value": "billing",
            "source": "heuristic",
        },
        # An unknown source from a newer SDK is stored, not refused.
        {
            "id": str(uuid4()),
            "type": "score",
            "trace_id": str(trace_id),
            "name": "x",
            "value": 1,
            "source": "future_source",
        },
    ]

    response = await client.post("/v1/ingest", json={"events": scores}, headers=a.headers)
    assert response.status_code == 202
    body = response.json()
    assert body["accepted_scores"] == 4
    assert body["rejected_scores"] == 0

    async with tenant_session(a.project_id) as session:
        rows = (
            await session.execute(
                text(
                    "SELECT name, data_type, value, value_text, source, comment, scored_at "
                    "FROM scores WHERE trace_id = :t OR observation_id = :o ORDER BY name"
                ),
                {"t": trace_id, "o": obs_id},
            )
        ).all()

    by_name = {r[0]: r for r in rows}
    assert set(by_name) == {"thumbs", "faithfulness", "category", "x"}
    assert by_name["thumbs"][1:4] == ("boolean", Decimal("1"), None)
    assert by_name["thumbs"][6] == t0, "the client's own timestamp is kept"
    assert by_name["faithfulness"][1:4] == ("numeric", Decimal("0.875"), None)
    assert by_name["faithfulness"][5] == "cites the doc"
    assert by_name["category"][1:4] == ("categorical", None, "billing")
    assert by_name["x"][4] == "future_source"


async def test_a_score_with_no_target_is_dropped_not_rejected(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    a, _ = tenants
    response = await client.post(
        "/v1/ingest",
        json={
            "events": [
                {"id": str(uuid4()), "type": "score", "name": "orphan", "value": 1},
                {
                    "id": str(uuid4()),
                    "type": "score",
                    "trace_id": str(uuid4()),
                    "name": "kept",
                    "value": 1,
                },
            ]
        },
        headers=a.headers,
    )
    assert response.status_code == 202, "one unusable score must not cost the batch"
    body = response.json()
    assert body["accepted_scores"] == 1
    assert body["rejected_scores"] == 1


async def test_replaying_scores_creates_no_duplicates(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    a, _ = tenants
    trace_id = uuid4()
    batch = {
        "scores": [{"id": str(uuid4()), "trace_id": str(trace_id), "name": "thumbs", "value": -1}]
    }
    for _ in range(3):
        assert (await client.post("/v1/ingest", json=batch, headers=a.headers)).status_code == 202

    count = await _scalar(
        a.project_id, "SELECT count(*) FROM scores WHERE trace_id = :t", t=trace_id
    )
    assert count == 1


async def test_a_score_may_arrive_before_its_trace(
    tenants: tuple[Tenant, Tenant], client: AsyncClient
) -> None:
    """No foreign key: the subject may still be in flight."""
    a, _ = tenants
    trace_id = uuid4()
    response = await client.post(
        "/v1/ingest",
        json={"scores": [{"id": str(uuid4()), "trace_id": str(trace_id), "name": "q", "value": 1}]},
        headers=a.headers,
    )
    assert response.status_code == 202
    assert response.json()["accepted_scores"] == 1
    assert await _scalar(a.project_id, "SELECT count(*) FROM traces WHERE id = :t", t=trace_id) == 0
