/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness. Deliberately does not touch the database.
         *
         *     Still fails when configuration is invalid: an instance that cannot read its
         *     own settings cannot serve, and reporting "ok" would hide that.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: Postgres is reachable and row-level security is in force.
         *
         *     Raising here is intentional. An instance whose runtime role bypasses RLS
         *     must never receive traffic, so a misconfigured DATABASE_URL fails the
         *     deploy loudly instead of silently serving cross-tenant data.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a Google sign-in and receive a session token */
        post: operations["sign_in_with_google_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out everywhere
         * @description Invalidate every session this user holds, on every device.
         *
         *     Stateless tokens cannot be deleted one at a time. Incrementing the user's
         *     session_version makes every token carrying the old one fail verification,
         *     so this is sign-out-everywhere by construction. Clearing the dashboard's
         *     cookie alone would leave a copied token valid until it expired.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a batch of traces, observations and scores
         * @description Accept a batch, write it, and return.
         *
         *     202 rather than 201: what is promised is durability, not that any particular
         *     row was newly created. A retry of an already-stored batch is a success and
         *     reports the same counts as the original.
         */
        post: operations["ingest_v1_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user and their projects */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a project's API keys */
        get: operations["list_keys_v1_projects__project_id__keys_get"];
        put?: never;
        /** Create an API key. The raw key is returned once. */
        post: operations["create_key_v1_projects__project_id__keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["revoke_key_v1_projects__project_id__keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List traces, newest first
         * @description Return one page of traces, newest first, without their payloads.
         *
         *     Ordered by `(started_at DESC, id DESC)`. The id is not decoration: traces
         *     written by one batch routinely share a timestamp, and it is the tiebreaker
         *     that gives the sort a total order, which is the whole basis for the cursor
         *     being stable across pages.
         *
         *     The range filters apply to `started_at` - event time, when the run actually
         *     happened - not to `created_at`, which is when this server received it. They
         *     differ whenever a client buffered, retried, or was offline.
         */
        get: operations["list_traces_v1_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One trace with all of its observations
         * @description Return one trace and every observation under it, payloads included.
         *
         *     Observations come back flat and ordered by started_at, with
         *     `parent_observation_id` intact; the client assembles the tree. Nesting is not
         *     validated here - the column carries no foreign key on purpose, so a parent
         *     that is still in flight is expected rather than corrupt.
         *
         *     A trace in another project is a 404, not a 403. Distinguishing the two would
         *     confirm that an id exists, which is a cross-tenant disclosure however small;
         *     RLS makes the row invisible and the absence is reported as absence.
         */
        get: operations["get_trace_v1_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyCreate */
        ApiKeyCreate: {
            /** Label */
            label?: string | null;
            /** Scopes */
            scopes: ("ingest" | "read")[];
        };
        /** ApiKeyCreated */
        ApiKeyCreated: {
            /** Api Key */
            api_key: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Prefix */
            key_prefix: string | null;
            /** Label */
            label: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Scopes */
            scopes: string[];
        };
        /** ApiKeyOut */
        ApiKeyOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Prefix */
            key_prefix: string | null;
            /** Label */
            label: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Scopes */
            scopes: string[];
        };
        /**
         * GoogleSignInRequest
         * @description What the dashboard forwards after Google redirects back to it.
         *
         *     `extra="forbid"`, unlike the ingest schemas: this is not a versioned SDK
         *     contract that must tolerate newer clients, it is our own dashboard, and an
         *     unexpected field here is a bug worth failing loudly on.
         */
        GoogleSignInRequest: {
            /** Code */
            code: string;
            /** Code Verifier */
            code_verifier: string;
            /** Nonce */
            nonce: string;
            /** Redirect Uri */
            redirect_uri: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestAccepted
         * @description Response body. 202, because durability is all that is promised here.
         *
         *     Counts are what was accepted for writing, not what was newly inserted -
         *     duplicates from a retry are accepted and silently deduplicated, and the
         *     client must not treat a lower number as an error.
         */
        IngestAccepted: {
            /** Accepted Observations */
            accepted_observations: number;
            /**
             * Accepted Scores
             * @default 0
             */
            accepted_scores: number;
            /** Accepted Traces */
            accepted_traces: number;
            /**
             * Rejected Observations
             * @default 0
             */
            rejected_observations: number;
            /**
             * Rejected Scores
             * @default 0
             */
            rejected_scores: number;
        };
        /**
         * IngestBatch
         * @description The POST /v1/ingest request body. Two envelopes are accepted.
         *
         *     Flat (what the Python SDK sends), a single stream discriminated by `type`::
         *
         *         {"events": [{"id": ..., "type": "trace", ...},
         *                     {"id": ..., "type": "generation", "trace_id": ..., ...},
         *                     {"id": ..., "type": "score", "trace_id": ..., "name": ..., "value": ...}]}
         *
         *     Nested, where observations are carried inside their trace::
         *
         *         {"traces": [{"id": ..., "observations": [...]}]}
         *
         *     The flat form is the one that suits a buffering client: spans finish
         *     independently and flush in whatever order they complete, so requiring the
         *     nesting would force the SDK to hold a trace open until its last child
         *     returned - and a long-running trace could not be reported until it ended.
         *     Nothing is lost by accepting it, because every observation carries its own
         *     trace_id and the router already creates a placeholder for a trace it has not
         *     seen yet.
         *
         *     Both normalise to the same internal shape before the router runs: `traces`
         *     for trace rows, `observations` for the flat remainder.
         */
        IngestBatch: {
            /** Observations */
            observations?: components["schemas"]["IngestObservation"][];
            /** Scores */
            scores?: components["schemas"]["IngestScore"][];
            /** Sdk Version */
            sdk_version?: string | null;
            /** Traces */
            traces?: components["schemas"]["IngestTrace"][];
        };
        /**
         * IngestObservation
         * @description One step inside a trace: an LLM generation, a span, or a discrete event.
         */
        IngestObservation: {
            /** Cached Tokens */
            cached_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Input */
            input?: unknown | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Level */
            level?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Model */
            model?: string | null;
            /** Name */
            name?: string | null;
            /** Output */
            output?: unknown | null;
            /** Parent Observation Id */
            parent_observation_id?: string | null;
            /** Prompt Name */
            prompt_name?: string | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Provider */
            provider?: string | null;
            /** Reasoning Tokens */
            reasoning_tokens?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Status Message */
            status_message?: string | null;
            /** Trace Id */
            trace_id?: string | null;
            /**
             * Type
             * @default span
             */
            type: string;
        };
        /**
         * IngestScore
         * @description A judgement about a trace or an observation.
         *
         *     `value` is a number, a boolean, or a short label; the router splits it into
         *     the typed columns. A score with neither target id is unusable and the
         *     router drops it - counted, not 4xxed, so one bad score cannot cost a batch.
         */
        IngestScore: {
            /** Comment */
            comment?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Observation Id */
            observation_id?: string | null;
            /** Scored At */
            scored_at?: string | null;
            /**
             * Source
             * @default human
             */
            source: string;
            /** Trace Id */
            trace_id?: string | null;
            /** Value */
            value: boolean | number | string;
        };
        /**
         * IngestTrace
         * @description One logical run through the client application, with its observations nested.
         */
        IngestTrace: {
            /** Ended At */
            ended_at?: string | null;
            /** Environment */
            environment?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name?: string | null;
            /** Observations */
            observations?: components["schemas"]["IngestObservation"][];
            /** Release */
            release?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Tags */
            tags?: string[];
            /** User Id */
            user_id?: string | null;
        };
        /** MeOut */
        MeOut: {
            /** Projects */
            projects: components["schemas"]["ProjectOut"][];
            user: components["schemas"]["UserOut"];
        };
        /**
         * ObservationDetail
         * @description One observation, with its payloads.
         *
         *     Returned flat, with `parent_observation_id` intact, ordered by started_at so
         *     the client can assemble the tree in a single pass.
         *
         *     A dangling `parent_observation_id` is normal, not corrupt: the column carries
         *     no foreign key on purpose, because batches split and retry independently and
         *     a parent may still be in flight. Render an orphan at the root; do not drop it.
         */
        ObservationDetail: {
            /** Cached Tokens */
            cached_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /**
             * Cost Usd
             * Format: decimal
             */
            cost_usd?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input */
            input?: unknown | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Level */
            level?: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Model */
            model?: string | null;
            /** Name */
            name?: string | null;
            /** Output */
            output?: unknown | null;
            /** Parent Observation Id */
            parent_observation_id?: string | null;
            /** Prompt Name */
            prompt_name?: string | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Provider */
            provider?: string | null;
            /** Reasoning Tokens */
            reasoning_tokens?: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status Message */
            status_message?: string | null;
            /** Total Tokens */
            total_tokens?: number | null;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /** Type */
            type: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "member";
        };
        /**
         * ScoreDetail
         * @description One score, as stored.
         *
         *     `value` is the numeric form (booleans as 1/0) and `value_text` the label;
         *     `data_type` says which one carries the judgement. Numeric values are
         *     strings for the same reason cost is: a JSON float would round them.
         */
        ScoreDetail: {
            /** Comment */
            comment?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data Type */
            data_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Observation Id */
            observation_id?: string | null;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
            /** Source */
            source: string;
            /** Trace Id */
            trace_id?: string | null;
            /**
             * Value
             * Format: decimal
             */
            value?: string | null;
            /** Value Text */
            value_text?: string | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Created */
            created: boolean;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Session Token */
            session_token: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * TraceDetail
         * @description GET /v1/traces/{trace_id}: one trace and every observation under it.
         *
         *     Empty `observations` is a 200, never a 404. A trace with no observations is
         *     a legitimate thing to look at - it may be open, or a stub whose spans have
         *     not landed - and the trace row itself is what the id addresses.
         *
         *     `scores` carries every score that names this trace or one of its
         *     observations, oldest first.
         */
        TraceDetail: {
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Ended At */
            ended_at?: string | null;
            /** Environment */
            environment?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name?: string | null;
            /**
             * Observation Count
             * @default 0
             */
            observation_count: number;
            /** Observations */
            observations: components["schemas"]["ObservationDetail"][];
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /** Release */
            release?: string | null;
            /**
             * Scores
             * @default []
             */
            scores: components["schemas"]["ScoreDetail"][];
            /** Sdk Version */
            sdk_version?: string | null;
            /** Session Id */
            session_id?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Total Cost Usd
             * Format: decimal
             * @default 0
             * @example 0.00123400
             */
            total_cost_usd: string;
            /**
             * Total Latency Ms
             * @default 0
             */
            total_latency_ms: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /** User Id */
            user_id?: string | null;
        };
        /**
         * TraceListItem
         * @description One row of GET /v1/traces.
         */
        TraceListItem: {
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Ended At */
            ended_at?: string | null;
            /** Environment */
            environment?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name?: string | null;
            /**
             * Observation Count
             * @default 0
             */
            observation_count: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /** Release */
            release?: string | null;
            /** Sdk Version */
            sdk_version?: string | null;
            /** Session Id */
            session_id?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Total Cost Usd
             * Format: decimal
             * @default 0
             * @example 0.00123400
             */
            total_cost_usd: string;
            /**
             * Total Latency Ms
             * @default 0
             */
            total_latency_ms: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /** User Id */
            user_id?: string | null;
        };
        /**
         * TraceListResponse
         * @description A page of traces plus the cursor that continues it.
         *
         *     `next_cursor` is opaque and must be echoed back verbatim. It encodes the
         *     (started_at, id) of the last row on this page, which is what makes paging
         *     stable when traces share a timestamp - id breaks the tie and the seek uses
         *     the same pair the ORDER BY does.
         */
        TraceListResponse: {
            /** Data */
            data: components["schemas"]["TraceListItem"][];
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    sign_in_with_google_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleSignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description redirect_uri is not an allowed sign-in destination */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Google rejected the code, or the ID token failed verification */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unverified email, or sign-up is restricted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Sign-in is not configured on this API */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingest_v1_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: string | null;
                "X-SDK-Version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Missing, unrecognised, or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Key lacks the 'ingest' scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Batch exceeds the configured size limits */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    list_keys_v1_projects__project_id__keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_key_v1_projects__project_id__keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key_v1_projects__project_id__keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such active key in a project you belong to */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traces_v1_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque cursor from a previous page. */
                cursor?: string | null;
                /** @description Exact trace name match. */
                name?: string | null;
                /** @description Exact match on the client's end-user id. */
                user_id?: string | null;
                /** @description Exact match on the client's session id. */
                session_id?: string | null;
                /** @description Exact match on the deployment environment. */
                environment?: string | null;
                /** @description Exact match on the release. */
                release?: string | null;
                /** @description Only traces carrying every one of these tags. Repeatable. */
                tag?: string[] | null;
                /** @description Only traces with started_at >= this (inclusive). */
                from?: string | null;
                /** @description Only traces with started_at < this (exclusive). */
                to?: string | null;
            };
            header?: {
                "X-Project-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListResponse"];
                };
            };
            /** @description Malformed cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, unrecognised, or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Key lacks the 'read' scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_v1_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: string | null;
            };
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Missing, unrecognised, or revoked API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Key lacks the 'read' scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such trace in this project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
