/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness. Deliberately does not touch the database.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: Postgres is reachable and row-level security is in force.
         *
         *     Raising here is intentional. An instance whose runtime role bypasses RLS
         *     must never receive traffic, so a misconfigured DATABASE_URL fails the
         *     deploy loudly instead of silently serving cross-tenant data.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a batch of traces and observations
         * @description Accept a batch, write it, and return.
         *
         *     202 rather than 201: what is promised is durability, not that any particular
         *     row was newly created. A retry of an already-stored batch is a success and
         *     reports the same counts as the original.
         */
        post: operations["ingest_v1_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List traces, newest first
         * @description Return one page of traces, newest first, without their payloads.
         *
         *     Ordered by `(started_at DESC, id DESC)`. The id is not decoration: traces
         *     written by one batch routinely share a timestamp, and it is the tiebreaker
         *     that gives the sort a total order, which is the whole basis for the cursor
         *     being stable across pages.
         *
         *     The range filters apply to `started_at` - event time, when the run actually
         *     happened - not to `created_at`, which is when this server received it. They
         *     differ whenever a client buffered, retried, or was offline.
         */
        get: operations["list_traces_v1_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One trace with all of its observations
         * @description Return one trace and every observation under it, payloads included.
         *
         *     Observations come back flat and ordered by started_at, with
         *     `parent_observation_id` intact; the client assembles the tree. Nesting is not
         *     validated here - the column carries no foreign key on purpose, so a parent
         *     that is still in flight is expected rather than corrupt.
         *
         *     A trace in another project is a 404, not a 403. Distinguishing the two would
         *     confirm that an id exists, which is a cross-tenant disclosure however small;
         *     RLS makes the row invisible and the absence is reported as absence.
         */
        get: operations["get_trace_v1_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestAccepted
         * @description Response body. 202, because durability is all that is promised here.
         *
         *     Counts are what was accepted for writing, not what was newly inserted -
         *     duplicates from a retry are accepted and silently deduplicated, and the
         *     client must not treat a lower number as an error.
         */
        IngestAccepted: {
            /** Accepted Traces */
            accepted_traces: number;
            /** Accepted Observations */
            accepted_observations: number;
            /**
             * Rejected Observations
             * @default 0
             */
            rejected_observations: number;
        };
        /**
         * IngestBatch
         * @description The POST /v1/ingest request body. Two envelopes are accepted.
         *
         *     Flat (what the Python SDK sends), a single stream discriminated by `type`::
         *
         *         {"events": [{"id": ..., "type": "trace", ...},
         *                     {"id": ..., "type": "generation", "trace_id": ..., ...}]}
         *
         *     Nested, where observations are carried inside their trace::
         *
         *         {"traces": [{"id": ..., "observations": [...]}]}
         *
         *     The flat form is the one that suits a buffering client: spans finish
         *     independently and flush in whatever order they complete, so requiring the
         *     nesting would force the SDK to hold a trace open until its last child
         *     returned - and a long-running trace could not be reported until it ended.
         *     Nothing is lost by accepting it, because every observation carries its own
         *     trace_id and the router already creates a placeholder for a trace it has not
         *     seen yet.
         *
         *     Both normalise to the same internal shape before the router runs: `traces`
         *     for trace rows, `observations` for the flat remainder.
         */
        IngestBatch: {
            /** Traces */
            traces?: components["schemas"]["IngestTrace"][];
            /** Observations */
            observations?: components["schemas"]["IngestObservation"][];
            /** Sdk Version */
            sdk_version?: string | null;
        };
        /**
         * IngestObservation
         * @description One step inside a trace: an LLM generation, a span, or a discrete event.
         */
        IngestObservation: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Trace Id */
            trace_id?: string | null;
            /** Parent Observation Id */
            parent_observation_id?: string | null;
            /**
             * Type
             * @default span
             */
            type: string;
            /** Name */
            name?: string | null;
            /** Model */
            model?: string | null;
            /** Provider */
            provider?: string | null;
            /** Input */
            input?: unknown | null;
            /** Output */
            output?: unknown | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Level */
            level?: string | null;
            /** Status Message */
            status_message?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
        };
        /**
         * IngestTrace
         * @description One logical run through the client application, with its observations nested.
         */
        IngestTrace: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Name */
            name?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Observations */
            observations?: components["schemas"]["IngestObservation"][];
        };
        /**
         * ObservationDetail
         * @description One observation, with its payloads.
         *
         *     Returned flat, with `parent_observation_id` intact, ordered by started_at so
         *     the client can assemble the tree in a single pass.
         *
         *     A dangling `parent_observation_id` is normal, not corrupt: the column carries
         *     no foreign key on purpose, because batches split and retry independently and
         *     a parent may still be in flight. Render an orphan at the root; do not drop it.
         */
        ObservationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /** Parent Observation Id */
            parent_observation_id?: string | null;
            /** Type */
            type: string;
            /** Name */
            name?: string | null;
            /** Model */
            model?: string | null;
            /** Provider */
            provider?: string | null;
            /** Input */
            input?: unknown | null;
            /** Output */
            output?: unknown | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
            /**
             * Cost Usd
             * Format: decimal
             */
            cost_usd?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Level */
            level?: string | null;
            /** Status Message */
            status_message?: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
        };
        /**
         * TraceDetail
         * @description GET /v1/traces/{trace_id}: one trace and every observation under it.
         *
         *     Empty `observations` is a 200, never a 404. A trace with no observations is
         *     a legitimate thing to look at - it may be open, or a stub whose spans have
         *     not landed - and the trace row itself is what the id addresses.
         */
        TraceDetail: {
            /**
             * Observation Count
             * @default 0
             */
            observation_count: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Total Cost Usd
             * Format: decimal
             * @default 0
             * @example 0.00123400
             */
            total_cost_usd: string;
            /**
             * Total Latency Ms
             * @default 0
             */
            total_latency_ms: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sdk Version */
            sdk_version?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Observations */
            observations: components["schemas"]["ObservationDetail"][];
        };
        /**
         * TraceListItem
         * @description One row of GET /v1/traces.
         */
        TraceListItem: {
            /**
             * Observation Count
             * @default 0
             */
            observation_count: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Total Cost Usd
             * Format: decimal
             * @default 0
             * @example 0.00123400
             */
            total_cost_usd: string;
            /**
             * Total Latency Ms
             * @default 0
             */
            total_latency_ms: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sdk Version */
            sdk_version?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /**
         * TraceListResponse
         * @description A page of traces plus the cursor that continues it.
         *
         *     `next_cursor` is opaque and must be echoed back verbatim. It encodes the
         *     (started_at, id) of the last row on this page, which is what makes paging
         *     stable when traces share a timestamp - id breaks the tie and the seek uses
         *     the same pair the ORDER BY does.
         */
        TraceListResponse: {
            /** Data */
            data: components["schemas"]["TraceListItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_v1_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                "X-SDK-Version"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Missing or unrecognised API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Batch exceeds the configured size limits */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traces_v1_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque cursor from a previous page. */
                cursor?: string | null;
                /** @description Exact trace name match. */
                name?: string | null;
                /** @description Exact match on the client's end-user id. */
                user_id?: string | null;
                /** @description Exact match on the client's session id. */
                session_id?: string | null;
                /** @description Only traces with started_at >= this (inclusive). */
                from?: string | null;
                /** @description Only traces with started_at < this (exclusive). */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListResponse"];
                };
            };
            /** @description Malformed cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or unrecognised API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_v1_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Missing or unrecognised API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such trace in this project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
